# docker-compose.yml para orquestrar os serviços do projeto.
# Este arquivo define os serviços: backend, frontend e banco de dados PostgreSQL.

version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meubanco
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@postgres:5432/meubanco
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mynetwork
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/app
    environment:
      STREAMLIT_SERVER_PORT: 8501
      STREAMLIT_SERVER_HEADLESS: "true"
      STREAMLIT_SERVER_ENABLE_CORS: "false"
      API_URL: "http://backend:8000"
    depends_on:
      - backend
    networks:
      - mynetwork
    ports:
      - "8501:8501"

networks:
  mynetwork:

volumes:
  postgres_data:
    # Volume nomeado para persistir dados do banco de dados
