services:
  postgres:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - mynetwork
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - mynetwork
    ports:
      - "8000:8000"

networks:
  mynetwork:

volumes:
  pgdata: